### ISSUE TITLE
Not a valid MML PSX BIN file

### ISSUE THREAD

**Issue by Oscarg73** [OmbraRD/DashEditor#1]
(I'm a total novice on this, sorry if I ask something stupid)

Hi, I'm getting this error continually when I try to extract the .bin files of the game (US version).

What I'm doing wrong?
![image](https://user-images.githubusercontent.com/25150787/96353536-5415ff80-10cd-11eb-9197-3a40a738c3e7.png)

**Comment by OmbraRD** [comment]
El programa no trabaja en el BIN de la ISO si no tienes que usar CDMage para extraer las carpetas y adentro de una encontrarás muchos archivos BIN.

Te puedes ayudar con los archivos .bat para extraer el contenido de todos a la vez.

Si quieres más detalles y ayuda me puedes encontrar en Discord con el usuario OmbraRD#0780.
