### ISSUE TITLE
Does this program not support the Japanese version?

### ISSUE THREAD

**Issue by 21-ko** [OmbraRD/DashEditor#2]
I even made a Japanese text table and applied it, but the result was a mess.
How should I solve this problem?

**Comment by OmbraRD** [comment]
The program was designed to work with the US version of the game. Extraction of BIN files for the Japanese version should work but not the text itself. Table should solve the decoding of text but won't solve the control codes which are probably completely different. To solve that you would have to modify the MSG.py file to be able to decode the them properly but it requires some reverse engineering to figure out the differences.

**Comment by 21-ko** [comment]
Thank you for your answer
I'll try a lot more
